language: java
jdk:
  - oraclejdk15
addons:
  sonarcloud:
    organization: "t-o-n-y-p"

before_install:
  - mvn install:install-file -Dfile=/home/travis/build/t-o-n-y-p/online-chess/src/lib/Stockfish-Java-2.0.2_2.jar -DgroupId=xyz.niflheim -DartifactId=stockfish -Dversion=2.0.2 -Dpackaging=jar

script:
  - mvn clean verify sonar:sonar -Pcoverage